name: Build and deploy Node.js app to Azure Web App - apptrackflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm install --prefix clientapp
          npm run build --prefix clientapp
          rm -rf clientapp/node_modules

      - name: Create .env file
        run: |
          echo "DB=mongodb+srv://cpxdev:75bf125f2096d93e6621ac3f8a65d9e1@db.rgavrls.mongodb.net" >> .env
          echo "LOGIN=99a1c89fc35d1fe01cdeeb6c50b6558ad40f1a7f09619d77e3fa3072286b4442873720015391abd6eeca635168732a3712971e348c4412449570cbe8292186581e5f74caabbece5ac8e05783cf4b011f605fb4fa82c13205bdf564fff6838d82c13f1a263aaddd670ca0aeb2e1220c648e6c952fd142d3533558c6a007b327cb" >> .env
          echo "d0e8798ead2c30ae5b487496443ed7d4c741aa919fbf865f82fe3fd61a0a8b25b3a24403f445a0f8d6de7a63dfd67ca55f0c53537aab69b9cc0e04827e133acb" >> .env
          echo "REFRESH=e1a85231d7104c2d4ee2e914efddaadb2669dce020664a7b4ded02372f56d64af899f8828816f7e9cf3228a4d57d692897506149e0bdacb26fd41bde2fd64953040055d404216a494d25dd9aec68946cbd3dbec43c3233942ca47f1d8969e75912f12cf2cea748822b383666a0430270cb2f56eb2438adf030b6efb017c08f968466b4e87fcc9af90a8f8be2c151299e61bec5198f8cdd74b63e484c1323e51641c5a52b714e00d3816d078fc5619dbe870052b52b219430e94d830353df8328168199e8ac72c8f6f796f808990e33d538460e2ecf183b9032b3a48dc855615f55ffa43e88da2b938b8fbdccd24d690c6d08f4ad58d28a3a54056b0d5377b17e" >> .env
          echo "CF_SECRET=0x4AAAAAABer7w554ZjyVy3a46XtL0ksGWE" >> .env

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ค่านี้ใช้ค่าตอน gen จาก azure app'
          slot-name: 'Production'
          package: .
          publish-profile: 'ค่านี้ใช้ค่าตอน gen จาก azure app'