name: Build and deploy Node.js + React (Vite) to Azure Web App - apptrackflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install root dependencies
        run: npm ci

      - name: Install and build client (Vite)
        run: |
          npm ci --prefix clientapp
          npm run build --prefix clientapp

      - name: Install API dependencies
        run: npm ci --prefix api

      - name: Prepare artifact for deployment
        run: |
          rm -rf release
          mkdir -p release/api
          # copy server code
          cp -R api/* release/api/
          # copy client build output
          mkdir -p release/client
          cp -R clientapp/dist/* release/client/
          # copy package.json and lockfile for Azure to install / startup
          cp package.json package-lock.json release/
          # create zip
          cd release
          zip -r ../release.zip ./*

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: nodeapp-artifact
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: nodeapp-artifact

      - name: Unzip artifact
        run: unzip release.zip -d release

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'apptrackflow'
          package: 'release'      # หรือใช้ 'release.zip' ก็ได้
