name: CI/CD – Node + Vite to Azure

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  NODE_VERSION: '20.x'            # เวอร์ชันที่ Azure รองรับ

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      # ---------- Build React (Vite) ----------
      - name: Install & build client
        run: npm run startproduction

      # ---------- สร้าง ZIP ----------
      - name: Package for deploy
        run: |
          cd api
          zip -r ../release.zip ./*

      - uses: actions/upload-artifact@v4
        with:
          name: webapp-package
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: webapp-package

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        id: deploy
        uses: azure/webapps-deploy@v3
        with:
          app-name: apptrackflow
          slot-name: Production
          package: release.zip
