name: Build and deploy Node.js app to Azure Web App - apptrackflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22.x'

    - name: Install client dependencies
      run: npm install --prefix clientapp

    - name: Build client
      run: npm run build --prefix clientapp

    - name: Copy built files to api/public
      run: mkdir -p api/public && cp -r clientapp/dist/* api/public/

    - name: Install server dependencies
      run: npm install --prefix api
      
    - name: 'Deploy to Azure Web App'
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'apptrackflow'
        slot-name: 'Production'
        package: .
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_806379C8F07B44A2A8A8EDB9B27523B2 }}
